### ISSUE TITLE
401 Unauthorised

### ISSUE THREAD

**Issue by dannybritto96** [initstring/dirty_sock#1]
401 Unauthorized with v2 script.

**Comment by initstring** [comment]
Hi Danny,
This generally means you are running a version of snapd that is not vulnerable. Also, with v2 it's possible that you triggered the system to update itself. If this was the case, it would have finished cleanly the first time you ran it, and then given you the 401 the second time.
If you waited long enough, though, you will have noticed it did end up creating the user account. Check the 'troubleshooting' section in the README.
