### ISSUE TITLE
Acces denied, login required

### ISSUE THREAD

**Issue by unstppbl** [initstring/dirty_sock#2]
Does this mean that the system is not vulnerable? 
```json
{"type":"error","status-code":401,"status":"Unauthorized","result":{"message":"access denied","kind":"login-required"}}
```

**Comment by initstring** [comment]
Hi mate,
Yes, it does. I believe the tool should have also printed a message saying that it is likely not vulnerable.
Per the README, run `snap version` to see your version number.
Closing issue, thanks!

**Comment by deedsgoodluv** [comment]
snap version
