### ISSUE TITLE
indented block error

### ISSUE THREAD

**Issue by syriusbughunt** [initstring/dirty_sock#4]
Hi,

I just tried running the dirty_sockv2.py and got the following error msg:

python3 dirty_sockv2.py
  File "dirty_sockv2.py", line 237
    main()
       ^
IndentationError: expected an indented block

I fixed the issue by adding 4 spaces on line 237, just an FYI if some users have the same issue.

**Comment by initstring** [comment]
Hi mate,

Thanks for opening a ticket! This is really weird. Line 237 in dirty_sockv2.py is actually a blank line and should not produce any error. Your error shows line 237 listing the main() function.

Are you using the original version posted in the GitHub repo?

Reference: https://github.com/initstring/dirty_sock/blob/master/dirty_sockv2.py

Thanks!

**Comment by initstring** [comment]
Closing this ticket as I am pretty sure it is not an issue. Please re-open if I'm wrong.
Thanks!
